us-east-1:
  ecr/iac-charts:
    prevent_destroy: true
    tags:
      Owner: squad-sre
      Lifecycle: stable
      System: iac
    inputs:
      scan_on_push: false
      other_account_access:
        - 631673599763
        - "075009827611"
