name: Pack and Push Helmchart

on:
  push:
    tags:
      - "*-[0-9]+.[0-9]+.[0-9]+"

jobs:
  pack-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Split Tag
        id: chart 
        shell: bash
        env:
          TAG: ${{ github.ref_name }}
        run: |
          TAG_SPLITED=$(echo $TAG | sed -E 's/(.*?)-([0-9]+.[0-9]+.[0-9]+)/\1#\2/')
          echo ::set-output name=NAME::$(cut -d'#' -f1 <<< "$TAG_SPLITED")
          echo ::set-output name=VERSION::$(cut -d'#' -f2 <<< "$TAG_SPLITED")
        
      - name: Add Chart.yaml
        shell: bash
        env:
          CHART_NAME: ${{ steps.chart.outputs.NAME }}
          CHART_VERSION: ${{ steps.chart.outputs.VERSION }}
        run: |
          cat > $CHART_NAME/Chart.yaml <<EOL
          apiVersion: v2
          name: $CHART_NAME
          version: $CHART_VERSION
          EOL

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Package and Push Chart to Amazon ECR
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.REPOSITORY_NAME }}
          CHART_NAME: ${{ steps.chart.outputs.NAME }}
          CHART_VERSION: ${{ steps.chart.outputs.VERSION }}
        run: |
          helm package $CHART_NAME
          helm push $CHART_NAME-$CHART_VERSION.tgz oci://$ECR_REGISTRY/$ECR_REPOSITORY
