## Reference: https://github.com/helm/chart-releaser-action
name: Helm Chart Release
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write  # for helm/chart-releaser-action to push chart release and create a release
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITFLOW_ACCESS_TOKEN }}"
          CR_SKIP_EXISTING: true
